# ============================================================
# Examples
# ============================================================

# Add example executables here.
#
# Example:
#
# add_executable(
#   example_app
#   example-main.cc
# )
#
# target_link_libraries(
#   example_app
#   PRIVATE
#   project_warnings
#   project_sanitizers
# )
