# ============================================================
# Core Libraries
# ============================================================

# Add reusable libraries here.
#
# Example:
#
# add_library(
#   MyLibrary
#   STATIC
#   my_library.cc
# )
#
# target_include_directories(
#   MyLibrary
#   PUBLIC
#   "${PROJECT_SOURCE_DIR}/include"
# )
#
# target_link_libraries(
#   MyLibrary
#   PRIVATE
#   project_warnings
#   project_sanitizers
# )
